directories:
  output: release
  buildResources: electron/resources
appId: com.codextemple.taskaccomplisher
productName: TaskAccomplisher
files:
  - filter:
      - dist/**
      - electron/**
      - tasks.json
      - package.json
mac:
  icon: electron/resources/icon.icns
win:
  icon: electron/resources/icon.ico
linux:
  icon: electron/resources/icon.png
  category: Utility
electronVersion: 40.0.0
